[project]
name = "chatbot-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed AMEKSA", email = "m.ameksa@uca.ac.ma" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "openai>=3.26.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
